version: '3.8'
services:
  api:
    build:
      args:
        - JDK_VERSION=${JDK_VERSION:-21-jdk-alpine}
        - JRE_VERSION=${JRE_VERSION:-21-jre-alpine}
      context: .
      dockerfile: Dockerfile.dev
    container_name: rest-template-api
    env_file:
      - .env
    depends_on:
      - db
